Repository AY2223S1-CS2103T-T11-2/tp, pull requests merged in 2022-11, with the labels that each got.

#197 Fix Issue 163
  docs/UserGuide.md
Labels: documentation, Priority.Low

#200 Fix sort salary bug
  src/main/java/seedu/intrack/model/internship/UniqueInternshipList.java
Labels: bug, Priority.Medium

#202 Fix bugs
  docs/UserGuide.md
  src/main/java/seedu/intrack/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/intrack/model/internship/TagsContainKeywordsPredicate.java
  src/test/java/seedu/intrack/model/internship/TagsContainKeywordsPredicateTest.java
Labels: bug, documentation, Priority.High

#199 Fix bugs
  docs/UserGuide.md
  src/main/java/seedu/intrack/logic/commands/AddTagCommand.java
  src/main/java/seedu/intrack/logic/commands/SortTimeCommand.java
  src/main/java/seedu/intrack/model/internship/Internship.java
  src/main/java/seedu/intrack/model/internship/UniqueInternshipList.java
  src/main/java/seedu/intrack/model/tag/Tag.java
  src/test/java/seedu/intrack/model/ModelManagerTest.java
Labels: bug, documentation, Priority.Medium

#201 Fix organisation of User Guide
  docs/UserGuide.md
Labels: documentation, Priority.High

#205 Fix UG bugs
  docs/UserGuide.md
Labels: documentation, Priority.Medium

#196 Add tests for DeleteTagCommand, AddTagCommand and their parsers
  src/test/java/seedu/intrack/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/intrack/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/intrack/logic/parser/AddTagCommandParserTest.java
  src/test/java/seedu/intrack/logic/parser/DeleteTagCommandParserTest.java
  src/test/java/seedu/intrack/model/internship/RemarkTest.java
  src/test/java/seedu/intrack/testutil/TypicalInternships.java
Labels: enhancement, Priority.Medium

#203 Fix isValidWebsite to only accept valid URL
  src/main/java/seedu/intrack/model/internship/Website.java
  src/test/data/JsonSerializableInTrackTest/duplicateInternshipInTrack.json
  src/test/java/seedu/intrack/model/internship/WebsiteTest.java
Labels: bug, Priority.High

#207 Update PPP
  docs/team/kangqiao322.md
Labels: documentation, Priority.High

#209 Update Jet's PPP
  docs/AboutUs.md
  docs/team/jetlfj.md
Labels: documentation, Priority.Medium

#210 Update ppp for Chantell
  docs/team/chantellyu.md
Labels: documentation

#211 Update PPP for Charlton
  docs/AboutUs.md
  docs/team/bigcrushes.md
  docs/team/jetlfj.md
Labels: documentation, Priority.Medium

#212 Update PPP for John
  docs/team/johnrhimawan.md
Labels: documentation, Priority.High

#216 Update DG use cases
  docs/DeveloperGuide.md
  docs/team/jetlfj.md
Labels: documentation, Priority.High

#218 Fix DG typo
  docs/DeveloperGuide.md
  docs/diagrams/StatusSequenceDiagram.puml
  docs/images/StatusSequenceDiagram.png
Labels: documentation

#217 Add assertions
  README.md
  src/main/java/seedu/intrack/logic/LogicManager.java
  src/main/java/seedu/intrack/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/intrack/logic/commands/SelectCommand.java
  src/main/java/seedu/intrack/logic/commands/StatusCommand.java
  src/main/java/seedu/intrack/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/intrack/logic/parser/SelectCommandParser.java
  src/main/java/seedu/intrack/logic/parser/StatusCommandParser.java
  src/main/java/seedu/intrack/ui/MainWindow.java
Labels: documentation, enhancement, Priority.Medium

#219 Add assertions
  src/main/java/seedu/intrack/logic/commands/AddTaskCommand.java
  src/main/java/seedu/intrack/logic/commands/DeleteCommand.java
  src/main/java/seedu/intrack/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/intrack/logic/parser/DeleteCommandParser.java
Labels: Priority.Medium

#221 Fix name errors
  docs/DeveloperGuide.md
Labels: documentation

#215 Reorder user stories and update NFR and glossary
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/kangqiao322.md
  src/main/java/seedu/intrack/logic/commands/SortTimeCommand.java
Labels: documentation

#220 Update naming for addtask portion of DG
  docs/AboutUs.md
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
Labels: documentation

#223 Add GUI summary
  docs/UserGuide.md
  docs/images/GUISummary.png
Labels: documentation, Priority.High

#226 Update use case for mail
  docs/DeveloperGuide.md
Labels: documentation

#228 Update FAQ in user guide
  docs/UserGuide.md
Labels: documentation, Priority.Medium

#231 Add assertions and make minor changes to documentation
  docs/AboutUs.md
  docs/Testing.md
  docs/_config.yml
  src/main/java/seedu/intrack/MainApp.java
  src/main/java/seedu/intrack/model/internship/Name.java
  src/main/java/seedu/intrack/model/internship/Position.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/intrack/model/internship/PositionTest.java
Labels: documentation, Priority.Medium

#232 Add testing
  src/test/java/seedu/intrack/logic/parser/AddTagCommandParserTest.java
  src/test/java/seedu/intrack/logic/parser/InTrackParserTest.java
  src/test/java/seedu/intrack/model/internship/InternshipTest.java
  src/test/java/seedu/intrack/testutil/InternshipUtil.java
Labels: Priority.Medium

#227 Add sort in developer guide
  docs/DeveloperGuide.md
  docs/diagrams/SortTimeActivityDiagram.puml
  docs/diagrams/SortTimeSequenceDiagram.puml
  docs/images/SortTimeActivityDiagram.png
  docs/images/SortTimeSequenceDiagram.png
Labels: documentation

#235 Update Ui images
  docs/UserGuide.md
  docs/images/UiBefore.png
  src/main/java/seedu/intrack/MainApp.java
Labels: documentation, Priority.Medium

#229 Fix bugs in AddSequenceDiagram and AddActivityDiagram
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddSequenceDiagram.png
  docs/images/AddTaskSequenceDiagram.png
  docs/team/johnrhimawan.md
Labels: bug, documentation

#237 Add more testing
  docs/diagrams/AddTaskActivityDiagram.puml
  docs/images/AddTaskActivityDiagram.png
  src/test/java/seedu/intrack/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/intrack/logic/commands/SortSalaryCommandTest.java
  src/test/java/seedu/intrack/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/intrack/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/intrack/logic/parser/StatusCommandParserTest.java
Labels: Priority.Medium

#241 Update PPP for johnrhimawan
  docs/team/johnrhimawan.md
Labels: documentation, Priority.High

#246 Update PPP
  docs/team/johnrhimawan.md
Labels: documentation, Priority.High

#242 Ppp updates
  docs/team/kangqiao322.md
Labels: documentation, Priority.Low

#247 [CS2101] Update User Guide
  docs/UserGuide.md
Labels: documentation
