Repository AY2223S1-CS2103T-T11-2/tp, pull requests merged in 2022-10, with the labels that each got.

#53 Add Status
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/internship/Address.java
  src/main/java/seedu/address/model/internship/Internship.java
  src/main/java/seedu/address/model/internship/Status.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedInternship.java
  src/main/java/seedu/address/ui/InternshipCard.java
  src/main/resources/view/InternshipListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidInternshipAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalInternshipsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditInternshipDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/internship/InternshipTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/address/testutil/EditInternshipDescriptorBuilder.java
  src/test/java/seedu/address/testutil/InternshipBuilder.java
  src/test/java/seedu/address/testutil/InternshipUtil.java
  src/test/java/seedu/address/testutil/TypicalInternships.java
Labels: enhancement, Priority.High

#64 Restrict Status field to only Offered, Progress, Rejected
  src/main/java/seedu/address/model/internship/Status.java
  src/main/java/seedu/address/storage/JsonAdaptedInternship.java
  src/main/java/seedu/address/ui/InternshipCard.java
  src/test/java/seedu/address/logic/commands/StatusCommandTest.java
Labels: enhancement

#79 Add Remark and RemarkCommand
  src/main/java/seedu/intrack/logic/commands/EditCommand.java
  src/main/java/seedu/intrack/logic/commands/RemarkCommand.java
  src/main/java/seedu/intrack/logic/commands/StatusCommand.java
  src/main/java/seedu/intrack/logic/parser/AddCommandParser.java
  src/main/java/seedu/intrack/logic/parser/CliSyntax.java
  src/main/java/seedu/intrack/logic/parser/InTrackParser.java
  src/main/java/seedu/intrack/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/intrack/model/internship/Internship.java
  src/main/java/seedu/intrack/model/internship/Remark.java
  src/main/java/seedu/intrack/model/util/SampleDataUtil.java
  src/main/java/seedu/intrack/storage/JsonAdaptedInternship.java
  src/main/java/seedu/intrack/ui/InternshipCard.java
  src/main/resources/view/InternshipListCard.fxml
  src/test/data/JsonSerializableInTrackTest/duplicateInternshipInTrack.json
  src/test/data/JsonSerializableInTrackTest/typicalInternshipsInTrack.json
  src/test/java/seedu/intrack/logic/commands/CommandTestUtil.java
  src/test/java/seedu/intrack/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/intrack/logic/parser/InTrackParserTest.java
  src/test/java/seedu/intrack/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/intrack/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/intrack/testutil/InternshipBuilder.java
Labels: enhancement

#83 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/RemarkActivityDiagram.puml
  docs/diagrams/RemarkSequenceDiagram.puml
  docs/images/RemarkActivityDiagram.png
  docs/images/RemarkSequenceDiagram.png
  src/main/java/seedu/intrack/logic/commands/RemarkCommand.java
Labels: documentation, Priority.Medium

#91 Include add command in developer guide
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddSequenceDiagram.png
  src/main/java/seedu/intrack/model/util/SampleDataUtil.java
Labels: documentation, Priority.Medium

#93 Include addtask command in developer guide
  docs/DeveloperGuide.md
  docs/diagrams/AddTaskActivityDiagram.puml
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/images/AddTaskActivityDiagram.png
  docs/images/AddTaskSequenceDiagram.png
Labels: documentation, Priority.Medium

#94 Include findn command in developer guide
  docs/DeveloperGuide.md
  docs/diagrams/FindNameActivityDiagram.puml
  docs/diagrams/FindNameSequenceDiagram.puml
  docs/images/FindNameActivityDiagram.png
  docs/images/FindNameSequenceDiagram.png
Labels: documentation, Priority.Medium

#86 Standardise order of variables
  src/main/java/seedu/intrack/logic/commands/AddTaskCommand.java
  src/main/java/seedu/intrack/logic/commands/EditCommand.java
  src/main/java/seedu/intrack/logic/commands/RemarkCommand.java
  src/main/java/seedu/intrack/logic/commands/StatusCommand.java
  src/main/java/seedu/intrack/logic/parser/AddCommandParser.java
  src/main/java/seedu/intrack/logic/parser/InTrackParser.java
  src/main/java/seedu/intrack/logic/parser/StatusCommandParser.java
  src/main/java/seedu/intrack/model/internship/Internship.java
  src/main/java/seedu/intrack/model/internship/Status.java
  src/main/java/seedu/intrack/model/util/SampleDataUtil.java
  src/main/java/seedu/intrack/storage/JsonAdaptedInternship.java
  src/main/java/seedu/intrack/ui/InternshipCard.java
  src/test/data/JsonInTrackStorageTest/invalidAndValidInternshipInTrack.json
  src/test/data/JsonInTrackStorageTest/invalidInternshipInTrack.json
  src/test/data/JsonSerializableInTrackTest/duplicateInternshipInTrack.json
  src/test/data/JsonSerializableInTrackTest/invalidInternshipInTrack.json
  src/test/data/JsonSerializableInTrackTest/typicalInternshipsInTrack.json
  src/test/java/seedu/intrack/logic/commands/CommandTestUtil.java
  src/test/java/seedu/intrack/logic/commands/EditCommandTest.java
  src/test/java/seedu/intrack/logic/commands/StatusCommandTest.java
  src/test/java/seedu/intrack/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/intrack/model/internship/RemarkTest.java
  src/test/java/seedu/intrack/model/internship/StatusTest.java
  src/test/java/seedu/intrack/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/intrack/testutil/EditInternshipDescriptorBuilder.java
  src/test/java/seedu/intrack/testutil/InternshipBuilder.java
  src/test/java/seedu/intrack/testutil/InternshipUtil.java
  src/test/java/seedu/intrack/testutil/TypicalInternships.java
Labels: enhancement, Priority.Medium

#100 Add filter command
  src/main/java/seedu/intrack/logic/commands/FilterCommand.java
  src/main/java/seedu/intrack/logic/parser/FilterCommandParser.java
  src/main/java/seedu/intrack/logic/parser/InTrackParser.java
  src/test/data/JsonSerializableInTrackTest/typicalInternshipsInTrack.json
  src/test/java/seedu/intrack/logic/commands/FilterCommandTest.java
  src/test/java/seedu/intrack/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/intrack/testutil/TypicalInternships.java
Labels: enhancement, Priority.High

#99 Add website field
  src/main/java/seedu/intrack/logic/commands/AddCommand.java
  src/main/java/seedu/intrack/logic/commands/AddTaskCommand.java
  src/main/java/seedu/intrack/logic/commands/EditCommand.java
  src/main/java/seedu/intrack/logic/commands/RemarkCommand.java
  src/main/java/seedu/intrack/logic/commands/StatusCommand.java
  src/main/java/seedu/intrack/logic/parser/AddCommandParser.java
  src/main/java/seedu/intrack/logic/parser/CliSyntax.java
  src/main/java/seedu/intrack/logic/parser/EditCommandParser.java
  src/main/java/seedu/intrack/logic/parser/ParserUtil.java
  src/main/java/seedu/intrack/model/internship/Address.java
  src/main/java/seedu/intrack/model/internship/Internship.java
  src/main/java/seedu/intrack/model/internship/Website.java
  src/main/java/seedu/intrack/model/util/SampleDataUtil.java
  src/main/java/seedu/intrack/storage/JsonAdaptedInternship.java
  src/main/java/seedu/intrack/ui/InternshipCard.java
  src/main/resources/view/InternshipListCard.fxml
  src/test/data/JsonSerializableInTrackTest/duplicateInternshipInTrack.json
  src/test/data/JsonSerializableInTrackTest/invalidInternshipInTrack.json
  src/test/data/JsonSerializableInTrackTest/typicalInternshipsInTrack.json
  src/test/java/seedu/intrack/logic/LogicManagerTest.java
  src/test/java/seedu/intrack/logic/commands/CommandTestUtil.java
  src/test/java/seedu/intrack/logic/commands/EditInternshipDescriptorTest.java
  src/test/java/seedu/intrack/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/intrack/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/intrack/logic/parser/ParserUtilTest.java
  src/test/java/seedu/intrack/model/InTrackTest.java
  src/test/java/seedu/intrack/model/internship/AddressTest.java
  src/test/java/seedu/intrack/model/internship/InternshipTest.java
  src/test/java/seedu/intrack/model/internship/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/intrack/model/internship/PositionContainsKeywordsPredicateTest.java
  src/test/java/seedu/intrack/model/internship/UniqueInternshipListTest.java
  src/test/java/seedu/intrack/model/internship/WebsiteTest.java
  src/test/java/seedu/intrack/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/intrack/testutil/EditInternshipDescriptorBuilder.java
  src/test/java/seedu/intrack/testutil/InternshipBuilder.java
  src/test/java/seedu/intrack/testutil/InternshipUtil.java
  src/test/java/seedu/intrack/testutil/TypicalInternships.java
Labels: enhancement, Priority.High

#109 Add tests associated to Task
  src/main/java/seedu/intrack/model/internship/Task.java
  src/test/java/seedu/intrack/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/intrack/model/internship/TaskTest.java
Labels: enhancement, Priority.Medium

#111 Add salary field and associated tests
  src/main/java/seedu/intrack/logic/commands/AddCommand.java
  src/main/java/seedu/intrack/logic/commands/AddTaskCommand.java
  src/main/java/seedu/intrack/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/intrack/logic/commands/EditCommand.java
  src/main/java/seedu/intrack/logic/commands/RemarkCommand.java
  src/main/java/seedu/intrack/logic/commands/StatusCommand.java
  src/main/java/seedu/intrack/logic/parser/AddCommandParser.java
  src/main/java/seedu/intrack/logic/parser/CliSyntax.java
  src/main/java/seedu/intrack/logic/parser/EditCommandParser.java
  src/main/java/seedu/intrack/logic/parser/ParserUtil.java
  src/main/java/seedu/intrack/model/internship/Internship.java
  src/main/java/seedu/intrack/model/internship/Phone.java
  src/main/java/seedu/intrack/model/internship/Salary.java
  src/main/java/seedu/intrack/model/util/SampleDataUtil.java
  src/main/java/seedu/intrack/storage/JsonAdaptedInternship.java
  src/main/java/seedu/intrack/ui/InternshipCard.java
  src/main/java/seedu/intrack/ui/SelectedInternshipCard.java
  src/main/resources/view/InternshipListCard.fxml
  src/main/resources/view/SelectedInternshipCard.fxml
  src/test/data/JsonInTrackStorageTest/invalidAndValidInternshipInTrack.json
  src/test/data/JsonInTrackStorageTest/invalidInternshipInTrack.json
  src/test/data/JsonSerializableInTrackTest/duplicateInternshipInTrack.json
  src/test/data/JsonSerializableInTrackTest/invalidInternshipInTrack.json
  src/test/data/JsonSerializableInTrackTest/typicalInternshipsInTrack.json
  src/test/java/seedu/intrack/logic/LogicManagerTest.java
  src/test/java/seedu/intrack/logic/commands/CommandTestUtil.java
  src/test/java/seedu/intrack/logic/commands/EditCommandTest.java
  src/test/java/seedu/intrack/logic/commands/EditInternshipDescriptorTest.java
  src/test/java/seedu/intrack/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/intrack/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/intrack/logic/parser/ParserUtilTest.java
  src/test/java/seedu/intrack/model/internship/InternshipTest.java
  src/test/java/seedu/intrack/model/internship/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/intrack/model/internship/PhoneTest.java
  src/test/java/seedu/intrack/model/internship/PositionContainsKeywordsPredicateTest.java
  src/test/java/seedu/intrack/model/internship/SalaryTest.java
  src/test/java/seedu/intrack/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/intrack/testutil/EditInternshipDescriptorBuilder.java
  src/test/java/seedu/intrack/testutil/InternshipBuilder.java
  src/test/java/seedu/intrack/testutil/InternshipUtil.java
  src/test/java/seedu/intrack/testutil/TypicalInternships.java
Labels: enhancement, Priority.High

#101 Add Sort command
  docs/DeveloperGuide.md
  src/main/java/seedu/intrack/logic/commands/SortCommand.java
  src/main/java/seedu/intrack/logic/parser/InTrackParser.java
  src/main/java/seedu/intrack/logic/parser/SortCommandParser.java
  src/main/java/seedu/intrack/model/InTrack.java
  src/main/java/seedu/intrack/model/Model.java
  src/main/java/seedu/intrack/model/ModelManager.java
  src/main/java/seedu/intrack/model/internship/Internship.java
  src/main/java/seedu/intrack/model/internship/UniqueInternshipList.java
  src/main/java/seedu/intrack/ui/SelectedInternshipCard.java
  src/test/java/seedu/intrack/logic/commands/AddCommandTest.java
  src/test/java/seedu/intrack/logic/commands/SortCommandTest.java
  src/test/java/seedu/intrack/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/intrack/model/ModelManagerTest.java
  src/test/java/seedu/intrack/model/internship/InternshipTest.java
  src/test/java/seedu/intrack/model/internship/UniqueInternshipListTest.java
  src/test/java/seedu/intrack/testutil/TypicalInternships.java
Labels: enhancement, Priority.High

#106 Add status test
  src/main/java/seedu/intrack/model/internship/Status.java
  src/test/java/seedu/intrack/logic/parser/StatusCommandParserTest.java
  src/test/java/seedu/intrack/model/internship/StatusTest.java
Labels: enhancement, Priority.Medium

#116 Add testing for Task commands and parsers
  src/main/java/seedu/intrack/logic/commands/AddTaskCommand.java
  src/main/java/seedu/intrack/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/intrack/logic/commands/SelectCommand.java
  src/test/java/seedu/intrack/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/intrack/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/intrack/logic/commands/SelectCommandTest.java
  src/test/java/seedu/intrack/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/intrack/logic/parser/SelectCommandParserTest.java
  src/test/java/seedu/intrack/testutil/InternshipBuilder.java
Labels: enhancement, Priority.High

#121 Allow valid URI to be appended to become valid URL
  src/main/java/seedu/intrack/model/internship/Website.java
Labels: enhancement, Priority.High

#127 Add JsonAdaptedTaskTest
  src/main/java/seedu/intrack/storage/JsonAdaptedTask.java
  src/test/java/seedu/intrack/storage/JsonAdaptedTaskTest.java
Labels: enhancement, Priority.Medium

#124 Update Edit command
  src/main/java/seedu/intrack/logic/commands/EditCommand.java
  src/main/java/seedu/intrack/logic/parser/EditCommandParser.java
  src/main/java/seedu/intrack/logic/parser/InTrackParser.java
  src/main/java/seedu/intrack/model/ModelManager.java
  src/test/java/seedu/intrack/logic/commands/EditCommandTest.java
  src/test/java/seedu/intrack/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/intrack/logic/parser/InTrackParserTest.java
Labels: enhancement, Priority.High

#126 Update UG and minor error fix for SortCommand
  docs/UserGuide.md
  src/main/java/seedu/intrack/logic/commands/SortCommand.java
  src/main/java/seedu/intrack/model/internship/Internship.java
  src/main/java/seedu/intrack/model/internship/UniqueInternshipList.java
Labels: documentation, enhancement, Priority.High

#129 Rename test internships
  src/test/data/JsonSerializableInTrackTest/typicalInternshipsInTrack.json
  src/test/java/seedu/intrack/logic/commands/FilterCommandTest.java
  src/test/java/seedu/intrack/logic/commands/FindNameCommandTest.java
  src/test/java/seedu/intrack/logic/commands/FindPositionCommandTest.java
  src/test/java/seedu/intrack/model/InTrackTest.java
  src/test/java/seedu/intrack/model/ModelManagerTest.java
  src/test/java/seedu/intrack/model/internship/InternshipTest.java
  src/test/java/seedu/intrack/model/internship/UniqueInternshipListTest.java
  src/test/java/seedu/intrack/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/intrack/storage/JsonInTrackStorageTest.java
  src/test/java/seedu/intrack/testutil/InternshipBuilder.java
  src/test/java/seedu/intrack/testutil/TypicalInternships.java
Labels: enhancement, Priority.Low

#130 Update UG - addtask
  docs/UserGuide.md
Labels: documentation, Priority.Medium

#136 Update internship card ui
  src/main/java/seedu/intrack/ui/InternshipCard.java
  src/main/java/seedu/intrack/ui/MainWindow.java
  src/main/java/seedu/intrack/ui/SelectedInternshipCard.java
  src/main/java/seedu/intrack/ui/UpcomingTaskCard.java
  src/main/java/seedu/intrack/ui/UpcomingTaskPanel.java
  src/main/resources/view/InternshipListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/UpcomingTaskCard.fxml
  src/main/resources/view/UpcomingTaskPanel.fxml
Labels: enhancement, Priority.High

#118 Add AddTagCommand and DeleteTagCommand
  src/main/java/seedu/intrack/commons/core/index/Index.java
  src/main/java/seedu/intrack/logic/commands/AddTagCommand.java
  src/main/java/seedu/intrack/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/intrack/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/intrack/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/intrack/logic/parser/InTrackParser.java
  src/main/java/seedu/intrack/model/internship/Internship.java
Labels: enhancement, Priority.High

#139 Update user guide
  docs/UserGuide.md
Labels: documentation, Priority.High

#140 Add sort salary
  src/main/java/seedu/intrack/logic/commands/SortCommand.java
  src/main/java/seedu/intrack/logic/commands/SortSalaryCommand.java
  src/main/java/seedu/intrack/logic/commands/SortTimeCommand.java
  src/main/java/seedu/intrack/logic/parser/SortCommandParser.java
  src/main/java/seedu/intrack/model/InTrack.java
  src/main/java/seedu/intrack/model/Model.java
  src/main/java/seedu/intrack/model/ModelManager.java
  src/main/java/seedu/intrack/model/internship/Salary.java
  src/main/java/seedu/intrack/model/internship/UniqueInternshipList.java
  src/main/java/seedu/intrack/ui/InternshipCard.java
  src/main/java/seedu/intrack/ui/SelectedInternshipCard.java
  src/main/resources/view/InternshipListCard.fxml
  src/test/java/seedu/intrack/logic/commands/AddCommandTest.java
  src/test/java/seedu/intrack/logic/commands/SortSalaryCommandTest.java
  src/test/java/seedu/intrack/logic/commands/SortTimeCommandTest.java
  src/test/java/seedu/intrack/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/intrack/model/ModelManagerTest.java
Labels: enhancement, Priority.High

#133 Add find tag command
  src/main/java/seedu/intrack/logic/commands/FindTagCommand.java
  src/main/java/seedu/intrack/logic/parser/FindTagCommandParser.java
  src/main/java/seedu/intrack/logic/parser/InTrackParser.java
  src/main/java/seedu/intrack/model/internship/TagsContainKeywordsPredicate.java
  src/test/data/JsonSerializableInTrackTest/typicalInternshipsInTrack.json
  src/test/java/seedu/intrack/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/intrack/logic/parser/FindPositionCommandParserTest.java
  src/test/java/seedu/intrack/logic/parser/FindTagCommandParserTest.java
  src/test/java/seedu/intrack/model/internship/InternshipTest.java
  src/test/java/seedu/intrack/model/internship/PositionContainsKeywordsPredicateTest.java
  src/test/java/seedu/intrack/model/internship/TagsContainKeywordsPredicateTest.java
  src/test/java/seedu/intrack/testutil/TypicalInternships.java
Labels: enhancement, Priority.High

#143 Fixed SortTimeCommand bug and updated UG for SortCommand
  docs/UserGuide.md
  src/main/java/seedu/intrack/logic/commands/SortSalaryCommand.java
  src/main/java/seedu/intrack/logic/commands/SortTimeCommand.java
Labels: bug, enhancement

#145 Fix bug where InTrack doesn't handle invalid dates
  src/main/java/seedu/intrack/logic/parser/AddTaskCommandParser.java
Labels: bug, Priority.Medium

#146 Add mail command
  src/main/java/seedu/intrack/logic/commands/MailCommand.java
  src/main/java/seedu/intrack/logic/parser/InTrackParser.java
Labels: enhancement, Priority.Medium

#155 Update version
  src/main/java/seedu/intrack/MainApp.java
Labels: enhancement, Priority.Medium

#156 Update UG to include mail
  docs/UserGuide.md
Labels: documentation, Priority.Medium

#158 Add new line for table display
  docs/UserGuide.md
Labels: bug, documentation

#159 Rename addressbook to InTrack in ```index.md```
  docs/index.md
Labels: documentation

#161 Userguidechantell
  docs/UserGuide.md
Labels: documentation, Priority.Medium
